name: chemical_CPA
channels:
  - conda-forge
dependencies:
  - python
  - adjusttext
  - matplotlib
  - numpy
  - pandas
  - scanpy
  - scipy
  - seaborn
  - scikit-learn
  - submitit
  - jupyter
  - jupytext
  - pytorch::pytorch
  - torchmetrics
  - cudatoolkit=11.3
  - dglteam::dgl
  - dglteam::dgllife
  - rdkit=2021.09.2
  - pytest
  - pyarrow
  - pre-commit
  - seml
  - py-spy
